### ISSUE TITLE
how to set QOS1?

### ISSUE THREAD

**Issue by TLS1000** [collin80/AWS_IOT#1]
Hi, thank you for picking up the Arduino ESP32 AWS-IOTsupport. I was using the hornbill version, but no commits since two years, and issues don't get replied to. That gives me the creeps when using the library.

I got it working, but publish failes every few minutes for a few consecutive attempts. Current publish frequency is 2s.  I don't think this isn't a real problem when posting at such high rate, but when I publish every minute I would like to have verification if the message arrived,. This can be done with QOS1 instead of using the default QOS0 if I understand correct.

Can I set QOS at runtime, or is the only way setting it in the library? at runtime is of course preferred, could you give example command for doing this?

**Comment by collin80** [comment]
Sure, you can set QOS1 and get confirmation back.

The easiest approach is probably to just copy the routine from the
AWS_IOT.cpp file and create a new one that does QOS1 instead by just
changing all QOS0 instances to QOS1 (which is also defined):

int AWS_IOT::publishQOS1(char *pubtopic,char *pubPayLoad)
{
IoT_Error_t rc;
IoT_Publish_Message_Params paramsQOS1;
paramsQOS1.qos = QOS1;
paramsQOS1.payload = (void *) pubPayLoad;
paramsQOS1.isRetained = 0;
paramsQOS1.payloadLen = strlen(pubPayLoad);
rc = aws_iot_mqtt_publish(&client, pubtopic, strlen(pubtopic), &paramsQOS1);
return rc;
}

I didn't personally test that but it ought to work fine. I don't actually
use this ESP32 library very much. In fact, I quit using it but there are a
few tweaks not found upstream so it could still be useful and I'm still
around answering emails. ;) I actually have more experience with the same
underlying code but on Raspberry Pi. And, I do use QOS1 there and it works
fine. Just remember that QOS1 causes the call to be blocking until either
it times out or Amazon replies so your program will halt while this
happens.

**Comment by TLS1000** [comment]
Hi Collin
blocking you say...? That's the path to the dark side...

I took a closer look at the other examples and there the message gets re-sent after a brief period (the next 'tick') when delivery fails. You know this but I'm writing this for others too see it also...


Thanks for the support!

`if(tick >= 5)  // Publish every 5secs

    {

        tempCelcius = thermoCouple.readCelsius();

        Irms = emon.calcIrms(1480);  // Calculate Irms only

        power = 230 * Irms;

        sprintf(payload,payloadFormat,tempCelcius,Irms,power); 

        if(AWS_CLIENT.publish(TOPIC_NAME,payload) == 0)

        {

            Serial.println(payload);

            tick = 0; // Publish successfull, wait for 5more seconds

        }

        else

        {

            Serial.println("Publish failed, Will try again after 1sec");

        }

    }

    else

    {

        tick++;

    }



    vTaskDelay(1000 / portTICK_RATE_MS);

}`
